TFB.Mvc/Models/ErrorViewModel.cs
namespace TFB.Mvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

TFB.Mvc/Models/MessageHistoryModel.cs
namespace TFB.Mvc.Models;

public class MessageHistoryModel
{
    public int MessageHistoryId { get; set; }
    public string Author { get; set; }
    public string Message { get; set; }
}

TFB.Mvc/Models/PersonalityUpdateRequestModel.cs
using System.ComponentModel.DataAnnotations;

namespace TFB.Mvc.Models
{
    public class PersonalityUpdateRequestModel
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public string PersonalityDescription { get; set; }
    }
}

TFB.Mvc/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TFB.Mvc.Models;

namespace TFB.Mvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

TFB.Mvc/Controllers/PersonalityController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using TFB.Models;
using TFB.Services;
using TFB.Mvc.Models;

namespace TFB.Mvc.Controllers;

public class PersonalityController : Controller
{
    private readonly ILogger<PersonalityController> _logger;
    private readonly IPersonalityService _personalityService;

    private const int _pageLimit = 10;
    public PersonalityController(ILogger<PersonalityController> logger, IPersonalityService personalityService)
    {
        _logger = logger;
        _personalityService = personalityService;
    } 

    [Route("personality/{personalityId}")]
    public async Task<IActionResult> Index(int personalityId)
    {
        var personalityRequest = new PersonalityRequest()
        {
            PersonalityId = personalityId, 
            IncludeMessageHistory = true
        };

        var personalities = await _personalityService.GetPersonalities(personalityRequest);

        var personalityDto = personalities.ToDTOList().First();
        
        return View(personalityDto);
    }

    [Route("personality/{personalityId}/edit")]
    public async Task<IActionResult> Edit(int personalityId)
    {
         var personalityRequest = new PersonalityRequest()
        {
            PersonalityId = personalityId,
            IncludeMessageHistory = true
        };

        var personalities = await _personalityService.GetPersonalities(personalityRequest);

        var personalityDto = personalities.ToDTOList().First();

        return View(personalityDto);
    }

    [Route("personality/{personalityId}/edit")]
    [HttpPost]
    public async Task<IActionResult> Edit(int personalityId, PersonalityUpdateRequestModel request)
    {
        var valid = base.TryValidateModel(request);

        var personalityRequest = new PersonalityRequest()
        {
            PersonalityId = personalityId,
            IncludeMessageHistory = true
        };

        var personalityDto = await _personalityService.GetPersonalities(personalityRequest);

        var returnedId = await _personalityService.UpdatePersonality(personalityId, request.Name, request.PersonalityDescription);

        if(returnedId == null)
        {
            _logger.LogError($"Could not update. {personalityId}");
        }

        return View(personalityDto.ToDTOList().FirstOrDefault());
    }


    [Route("personalities/{page?}")]
    public async Task<IActionResult> Personalities(int page = 1)
    {
        var request = new PersonalityRequest()
        {
            IncludeMessageHistory = true
        };

        var personalities = await _personalityService.GetPersonalities(request);

        return View(personalities.ToDTOList().ToPagedList(page, _pageLimit));
    }
}

TFB.Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TFB.Mvc/Views/Personality/Edit.cshtml
@model TFB.DTOs.Personality

@{
    ViewData["Title"] = "Edit Personality Page";
}

@using (Html.BeginForm("Edit", "Personality", FormMethod.Post))
{
    <div>
        <label for="name">Name:</label>
        @Html.TextBoxFor(m => m.Name)
    </div>

    <div>
        <label for="PersonalityDescription">Personality:</label>
        @Html.TextAreaFor(m => m.PersonalityDescription, new { cols = 50, rows = 10 })
    </div>

    <button type="submit">Update Personality</button>
}

TFB.Mvc/Views/Personality/Index.cshtml
@model TFB.DTOs.Personality

@{
    ViewData["Title"] = "Personality Page";
}

<div class="row">
    <div class="col-xs-12 col-md-8">
        <p class="h3">@Model.Name</p>
        <p>
            <p>
                <strong>Command:</strong>
            </p>
            @Model.Command
        </p>
        <p>
            <p>
                <strong>Command:</strong>
            </p>
            @Model.PersonalityDescription
        </p>
        <p>
            <p>
                <strong>AI Model:</strong>
            </p>
            @(Model.Model ?? "gpt-3.5")
        </p>
    </div>
    <div class="col-xs-12 col-md-4">
        @await Html.PartialAsync("_Messages", Model.MessageHistory)
    </div>
</div>

TFB.Mvc/Views/Personality/Personalities.cshtml
@model X.PagedList.IPagedList<TFB.DTOs.Personality>
@using X.PagedList.Mvc.Core;

@{
    ViewData["Title"] = "Personality Page";
}

<div class="row">
    <ul class="list-group list-group-flush">
        @foreach (var personality in Model)
        {
            <li class="list-group-item">
                <div class="row">
                    <div class="col-4">
                        <a class="fw-bold" href="@Url.Action("Index", new { personality.PersonalityId })">
                            <span>@personality.Name</span>
                        </a>
                    </div>
                    <div class="col-2 offset-3 align-content-end">
                        <span>@personality.Command</span>
                    </div>
                    <div class="col-2 align-content-end">
                        <span>@personality.MessageHistory.Count Messages</span>
                    </div>
                </div>
            </li>
        }
    </ul>
</div>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Personalities", 
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

TFB.Mvc/Views/Personality/_Messages.cshtml
@model List<TFB.DTOs.Message>

@{
    Layout = null;
}
<div class="h3 mb-4">Message History</div>
@foreach (var message in Model)
{
    <div class="card mb-2">
        <div class="card-body">
            <div class="row justify-content-between mb-2">
                <strong class="col-4">@message.Author</strong>
                <strong class="col-6 text-uppercase">@message.DatePosted</strong>
            </div>
            <p>
                @message.Value
            </p>
        </div>
    </div>
}

TFB.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TFB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TFB.Mvc.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TFB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Personality" asp-action="Personalities">Personalities</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @(DateTime.Now.Year.ToString()) - TFB.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>